spring:
  config:
    import: file:.env[.properties]
  application:
    name: geral-car

  servlet:
    multipart:
      max-file-size: 5MB


  datasource:
    url: jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
    password: ${ENV_POSTGRES_PASSWORD}
    username: ${ENV_POSTGRES_USER}

    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update
    generate-ddl: true

  web:
    error:
      include-stacktrace: never

file:
  upload-dir: imagens
